#define CIRCLE    "/d/coronos/w/chi/city/circle/"
#define R_ESTATE  "/d/coronos/w/chi/city/r_estate/"
#define SHOPS     "/d/coronos/w/chi/city/shops/"
#define OBJ       "/d/coronos/w/chi/city/obj/"
#define STREETS   "/d/coronos/w/chi/city/streets/"
